OptimaLK/laboratory

lab-admin-ui/src/main/java/ru/optima/controller/EquipmentController.java, lab-admin-ui/src/main/java/ru/optima/controller/MainController.java, lab-admin-ui/src/main/java/ru/optima/util/PathCreator.java
PathCreator - генератор
Изменен MainController
Изменены ссылки в EqupmentController и UserController
по типу:
@GetMapping("/users")
public String adminUsersPage(Model model, SecurityContextHolder auth) {
............
return pathCreator.createPath(auth, "users");  // < если входить от имени chief  будет возвращено "chief/users" 
}
=> добавил генератор ссылок для контролеров

lab-admin-ui/src/main/java/ru/optima/controller/MainController.java, lab-admin-ui/src/main/resources/static/css/header_style.css, lab-admin-ui/src/main/resources/templates/admin/index.html, lab-admin-ui/src/main/resources/templates/fragments/chief/header.html
=> Главная страница

lab-admin-ui/src/main/java/ru/optima/controller/UserController.java, lab-admin-ui/src/main/java/ru/optima/controller/WorkController.java, lab-admin-ui/src/main/java/ru/optima/repr/WorkRepr.java, lab-admin-ui/src/main/java/ru/optima/service/WorkServiceImpl.java, lab-database/src/main/java/ru/optima/persist/model/User.java
ничего особого не сделал.
Стер код без функций.
Подправил create и delete методы в UserController и EquipmentController - теперь CRUD в контроллерах работает, работает.
=> Task работа над контроллерами

lab-admin-ui/src/main/java/ru/optima/controller/BagController.java, lab-admin-ui/src/main/java/ru/optima/repr/BagRepr.java, lab-admin-ui/src/main/java/ru/optima/repr/EquipmentRepr.java, lab-admin-ui/src/main/java/ru/optima/repr/UserRepr.java, lab-admin-ui/src/main/java/ru/optima/service/BagService.java, lab-admin-ui/src/main/java/ru/optima/service/BagServiceImpl.java, lab-admin-ui/src/main/resources/application.properties, lab-admin-ui/src/main/resources/templates/executor/equipments.html, lab-database/src/main/java/ru/optima/persist/model/User.java, lab-database/src/main/java/ru/optima/persist/model/equipments/Bag.java, lab-database/src/main/java/ru/optima/persist/model/equipments/Equipment.java, lab-database/src/main/java/ru/optima/persist/repo/BagRepository.java, lab-database/src/main/resources/db/changelog/db.changelog-master.xml, lab-database/src/main/resources/db/changelog/v-2.2/db.changelog-20210515-034630388.xml, lab-database/src/main/resources/liquibase-maven-plugin.properties, pom.xml
- Создал много сумок у одного пользователя.
в данный момент исполнитель работает только с последней созданной сумкой, в дальнейшем мы добавим условие, чтобы он после выезда создавал новую сумку (и он автоматически будет работать с последней)
-теперь во вкладке оборудования, можно взять/положить оборудование в сумке, при добавлении оборудование, меняется поле Taken, где тру, в сумке и фолсе нет в сумке.
=> Добавил сумку

lab-admin-ui/src/main/java/ru/optima/controller/BagController.java, lab-admin-ui/src/main/java/ru/optima/service/BagService.java, lab-admin-ui/src/main/java/ru/optima/service/BagServiceImpl.java, lab-database/src/main/resources/db/changelog/db.changelog-master.xml, lab-database/src/main/resources/db/changelog/v-2.3/db.changelog-20210507-165358610.xml, lab-database/src/main/resources/db/changelog/v-2.3/insert-default-users-roles.sql, util/src/main/java/ExcelBase/ExcelSQL.java
Баг: когда заходил под другим пользователем, при определенных манипуляциях мог положить повторно одно и тоже оборудование, плюс вылетала ошибка когда у нового пользователя (у которого еще не было сумки) при попытке положить не свое оборудование вылетала 500 ошибка
=> Исправил Баг с множеством исполнителей

lab-admin-ui/src/main/java/ru/optima/controller/MainController.java, lab-admin-ui/src/main/java/ru/optima/controller/WorkController.java, lab-admin-ui/src/main/java/ru/optima/repr/WorkRepr.java, lab-admin-ui/src/main/java/ru/optima/service/WorkService.java, lab-admin-ui/src/main/java/ru/optima/service/WorkServiceImpl.java, lab-admin-ui/src/main/java/ru/optima/util/PathCreator.java, lab-admin-ui/src/main/resources/templates/chief/work_form.html, lab-admin-ui/src/main/resources/templates/executor/index.html, lab-admin-ui/src/main/resources/templates/executor/work_form.html, lab-admin-ui/src/main/resources/templates/executor/works.html, lab-database/src/main/java/ru/optima/persist/model/Work.java, lab-database/src/main/java/ru/optima/persist/repo/WorkRepository.java, lab-database/src/main/resources/db/changelog/db.changelog-master.xml, lab-database/src/main/resources/db/changelog/v-2.4/db.changelog-20210517-211119296.xml, lab-database/src/main/resources/db/changelog/v-2.4/insert-default-works.sql
ацепило
WorkRepository
WorkService
WorkController
works.html
везде чуть-чуть
Нашел и добавил Фронт (в index страницах лежит)
в базу работы не добавлял...
ДОДЕЛАЛ: отметить работу завершенной и выбор команды
=>  Доработка : на странице работ каждого пользователя отображаются только его работы.

lab-admin-ui/src/main/java/ru/optima/controller/WorkController.java, lab-admin-ui/src/main/java/ru/optima/service/UserService.java, lab-admin-ui/src/main/java/ru/optima/service/UserServiceImpl.java, lab-database/src/main/java/ru/optima/persist/repo/UserRepository.java
1) В списке назначаемых на работу сотрудников только  счастливые обладатели ROLE_EXECUTOR
2) В списке набора команды только сотрудники, которых еще не назначили на выполнение этой работы
=> Исправления (подправил по полученным замечаниям)

lab-admin-ui/src/main/java/ru/optima/controller/BagController.java, lab-admin-ui/src/main/java/ru/optima/service/BagService.java, lab-admin-ui/src/main/java/ru/optima/service/BagServiceImpl.java, lab-admin-ui/src/main/resources/templates/executor/bag.html, lab-admin-ui/src/main/resources/templates/fragments/executor/header.html
На основе Артура Дописал сумку, что скажете?
=> Страничка сумки, плюс очистка всей сумки

lab-admin-ui/src/main/java/ru/optima/controller/WorkController.java, lab-admin-ui/src/main/resources/static/css/works.css, lab-admin-ui/src/main/resources/templates/chief/work_form.html, lab-admin-ui/src/main/resources/templates/chief/works.html, lab-admin-ui/src/main/resources/templates/fragments/admin/header.html, lab-admin-ui/src/main/resources/templates/fragments/chief/header.html, lab-admin-ui/src/main/resources/templates/fragments/director/header.html, lab-admin-ui/src/main/resources/templates/fragments/executor/header.html
- создание работы без исполнителя (при создании работы исполнитела можно не выбирать, это поле необязательное)
- в списке работ у Шефа отображается один исполнитель
- если исполнитель не назначен, то появляется значок добавить
- отображение зелёного и красного значка, если Исполнитель выполнил работу, при нажатии на зелёный значок, работа переходит в архив (пока просто ссылка), при нажатии на красный значок, работа снова приобретает статус активной
=> Добавлено:

lab-admin-ui/src/main/java/ru/optima/controller/BagController.java, lab-admin-ui/src/main/java/ru/optima/controller/EquipmentController.java, lab-admin-ui/src/main/java/ru/optima/repr/EquipmentRepr.java, lab-admin-ui/src/main/java/ru/optima/service/BagServiceImpl.java, lab-admin-ui/src/main/resources/templates/executor/equipments.html, lab-database/src/main/java/ru/optima/persist/model/equipments/Equipment.java, lab-database/src/main/resources/db/changelog/db.changelog-master.xml, lab-database/src/main/resources/db/changelog/v-3.1/db.changelog-20210525-131735929.xml
- Если кто-то взял оборудование, другой испытатель видит кто именно его взял
=> Фича кнопочки с фамилиями

lab-admin-ui/src/main/resources/templates/chief/users.html, lab-admin-ui/src/main/resources/templates/executor/users.html, lab-admin-ui/src/main/resources/templates/executor/works.html, lab-admin-ui/src/main/resources/templates/fragments/admin/header.html, lab-admin-ui/src/main/resources/templates/fragments/chief/header.html, lab-admin-ui/src/main/resources/templates/fragments/director/header.html, lab-admin-ui/src/main/resources/templates/fragments/executor/header.html, lab-admin-ui/src/main/resources/templates/fragments/secretary/header.html
На вкладке "Пользователи" иконки "редактировать" и "удалить" находятся напротив того пользователя под которым зашли, то есть каждый пользователь может редактировать и удалять только себя.
Подредактировал внешний вид вкладки "Пользователи".
Изменение цвета карточек на вкладке "Список работ" (цвет меняется при нажатии на кнопку "На проверку" и при загрузке страницы, карточки, которые на проверке имеют зелёный цвет)
=> Вкладки "Пользователи" и "Список работ"

lab-admin-ui/src/main/java/ru/optima/controller/EquipmentController.java, lab-admin-ui/src/main/java/ru/optima/service/CategoryService.java, lab-admin-ui/src/main/java/ru/optima/service/CategoryServiceImpl.java, lab-admin-ui/src/main/java/ru/optima/service/EquipmentServiceImpl.java, lab-admin-ui/src/main/resources/templates/fragments/tools_menu.html, lab-database/src/main/java/ru/optima/persist/model/equipments/Category.java, lab-database/src/main/java/ru/optima/persist/model/equipments/Equipment.java, lab-database/src/main/java/ru/optima/persist/repo/CategoryRepository.java, lab-database/src/main/java/ru/optima/persist/repo/EquipmentRepository.java, lab-database/src/main/resources/db/changelog/db.changelog-master.xml, lab-database/src/main/resources/db/changelog/v-3.2/db.changelog-20210524-174249014.xml, lab-database/src/main/resources/db/changelog/v-3.2/insert-default-equp-category.sql
1) Добавлены категории к оборудованию
(в базе к уже существующему оборудованию добавлены в случайном порядке существующие категории)
2) создан репозитории и сервисный слой для категорий + легкие дополнения к оборудованию
3) настроено отображение, переключение между вкладками - работает, есть "неловкие" моменты, но это требует обсуждения
=> Task category

lab-admin-ui/src/main/resources/static/css/equipments.css, lab-admin-ui/src/main/resources/templates/executor/equipments.html
добавлен js сравнивающий крайний срок поверки оборудования с текущей датой,  при истечении срока, оборудование взять нельзя 
прошу внимательно проверить работоспособность, опыта особого нет, но вроде настроил и все работает -> в базу с прошедшим сроком поверки оборудование не вносил, для тестирования менял вручную  
скрипт добавлен только на страницу выбора оборудования на странице executor
выбор оборудования на странице шефа на настоящий момент не работает -> скрипт можно добавить после 
ps: при просмотре логики работы выбора оборудования -> в шаблоне есть излишний код, лишняя кнопка в switch, как понимаю связанный с наличием значения null в базе... 
может имеет смысл поправить, пока не распространилось на шаблон шефа?!
=> Проверка срока поверки

lab-admin-ui/src/main/resources/static/css/equipments.css, lab-admin-ui/src/main/resources/templates/chief/equipments.html, lab-admin-ui/src/main/resources/templates/executor/equipments.html
1) исправил косяк с секундным появлением надписи "На поверку"
2) добавил: за 30 дней прибор становился желтым, выделена дата поверки
3) добавил версию на страницу шефа.
=> Оборудование (активные)

lab-admin-ui/src/main/resources/templates/fragments/secretary/header.html, lab-admin-ui/src/main/resources/templates/secretary/equipment_form.html, lab-admin-ui/src/main/resources/templates/secretary/equipments.html, lab-admin-ui/src/main/resources/templates/secretary/index.html, lab-admin-ui/src/main/resources/templates/secretary/user_form.html, lab-admin-ui/src/main/resources/templates/secretary/users.html, lab-admin-ui/src/main/resources/templates/secretary/work_form.html, lab-admin-ui/src/main/resources/templates/secretary/works.html
Фактически:
Делал в соответствии с общей структурой проекта, получилась некая смесь из страниц executor  и chief, но в своей папке.
Из наблюдений:
1) фрагменты за все время разработки остались неизменны, но фактически существуют в нескольких копиях -> можно оставить один вариант на всех 
2) страница users и user_form идентичны с executor -> следует подумать над функциями, возможно можно оставить один вариант 
3) страница works и work_form идентичны с chief -> следует подумать над функциями, возможно можно оставить один вариант
=> Sprint 4 secretary

lab-admin-ui/src/main/java/ru/optima/controller/UserController.java, lab-admin-ui/src/main/resources/templates/executor/user_form.html
исправление ошибки с редактированием у executora
=> Sprint 4 user edit

lab-admin-ui/src/main/java/ru/optima/controller/WorkController.java, lab-admin-ui/src/main/resources/templates/chief/works.html, lab-admin-ui/src/main/resources/templates/secretary/works.html
Добавил проверку на удаления работы шефу и секретарю.
2 разных варианта 
1) простой
2) с дополнительной проверкой
=> Sprint 4 check to delete

lab-admin-ui/src/main/java/ru/optima/controller/EquipmentController.java, lab-admin-ui/src/main/java/ru/optima/service/EquipmentServiceImpl.java, lab-admin-ui/src/main/resources/templates/chief/equipment_form.html
Исправлено создание нового оборудования
=> Sprint 4 save equipment

lab-admin-ui/src/main/java/ru/optima/controller/EquipmentController.java, lab-admin-ui/src/main/java/ru/optima/controller/MainController.java, lab-admin-ui/src/main/java/ru/optima/service/BagServiceImpl.java, lab-admin-ui/src/main/java/ru/optima/service/EquipmentServiceImpl.java, lab-admin-ui/src/main/resources/static/css/header_style.css, lab-admin-ui/src/main/resources/templates/chief/equipment_form.html, lab-admin-ui/src/main/resources/templates/chief/work_form.html
Когда Исполнитель начинает ложить оборудование он делает это сразу в создоваемую сумку, котороая в последствии несет 2 проблемы:
Руководитель на главной странице 500 из-за не полной информации по сумке.
Когда второй пользователь начинает собирать свою сумку, первая пропадает и пиши пропало.
500 ошибка при редактировании оборудования. Проблема в не передачи категории. категория не может быть null
=> Исправления ошибок:

lab-admin-ui/src/main/resources/templates/executor/works.html
Добавил наименование заказчика в списке работ исполнителя
=> Добавил наименование заказчика  в списке работ исполнителя

lab-admin-ui/src/main/java/ru/optima/controller/WorkController.java, lab-admin-ui/src/main/java/ru/optima/repr/WorkRepr.java, lab-admin-ui/src/main/java/ru/optima/service/WorkServiceImpl.java, lab-admin-ui/src/main/resources/static/css/works.css, lab-admin-ui/src/main/resources/templates/chief/equipment_form.html, lab-admin-ui/src/main/resources/templates/chief/works.html, lab-admin-ui/src/main/resources/templates/secretary/work_form.html, lab-admin-ui/src/main/resources/templates/secretary/works.html, lab-database/src/main/java/ru/optima/persist/model/Work.java, lab-database/src/main/resources/db/changelog/db.changelog-master.xml, lab-database/src/main/resources/db/changelog/v-3.6/db.changelog-20210620-114316970.xml
Добавлена возможность изменять ответственного и срок исполнения.
Немного увеличил шрифты.
=> Редактирование списка работ у шефа и секретаря.
